[package]
name = "burn-pra"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.13.2", features = ["autodiff", "burn-train", "train", "wgpu"] }
image = "0.25.2"
yolox-burn = { git = "https://github.com/tracel-ai/models", package = "yolox-burn", features = ["pretrained"] }
